### ISSUE TITLE
Polygon

### ISSUE THREAD

**Issue by AntonMashnin** [axelarnetwork/axelar-docs#10]
- Polygon - we have noticed that outdated versions bor and heimdall are used, so we have updated them also

Also we have set the following infura URL in the: `~/.heimdalld/config/heimdall-config.toml` file:

`eth_rpc_url = wss://goerli.infura.io/ws/v3/fcf0xxxxxxxxxxxxx`

Maybe we need to describe this process in the documentation in more detail because it is not obvious to regular users?

**Comment by ggutoski** [comment]
Can you suggest some specific edits to the instructions in the draft PR #13 ?

**Comment by AntonMashnin** [comment]
To update Heimdall to the latest version the customer needs to do:
```
cd ~/
git clone https://github.com/maticnetwork/heimdall
cd heimdall
git checkout vX.X.X (where X.X.X depends on the latest version, the latest version was v0.2.9)
make install
```

The latest version of the Heimdall tool you can find here: https://github.com/maticnetwork/heimdall/releases

**Comment by AntonMashnin** [comment]
To update Bor to the latest version the customer needs to do:
```
cd ~/
git clone https://github.com/maticnetwork/bor
cd bor
git checkout vX.X.XX-tmp-span-hotfix  (where X.X.XX depends on the latest version, the latest version was v0.2.14)
make bor-all
sudo ln -nfs ~/bor/build/bin/bor /usr/bin/bor
sudo ln -nfs ~/bor/build/bin/bootnode /usr/bin/bootnode
bor version
```

The latest version of the Heimdall tool you can find here: https://github.com/maticnetwork/bor/releases

**Comment by ggutoski** [comment]
Ah ok thanks.  I think existing instructions are pretty clear about getting the latest version.  I'll just update the version number and leave it there.
