### ISSUE TITLE
Remaining Major Docs work for Amplifier

### ISSUE THREAD

**Issue by StephenFluin** [axelarnetwork/axelar-docs#1001]
* [x] updateVerifierSet - make a change to the verifier set for a chain (on the Axelar Network)
* [x] checkIfInActiveSet - see if a verifier is part of the active set for a gateway (https://github.com/axelarnetwork/axelar-docs/pull/981)
* [x] getVerifierSetProof - get a proof for the change of a verifier set that can be used on a destination gateway.
* [x] rotate_signers - propagate changes in verifiers for a connected chain to that chains' gateway
* [x] supplyRewards - how do I send rewards to my pool so that verifiers are incentivized?
* [x] verifyMessages - relay a source chain transaction to the Axelar relayers so that it's submitted on-chain
* [x] routeMessages - Axelar method to trigger routing of a message once it has been voted on successfully
* [x] constructProof - Get a proof for a message from the axelar network so that it can be relayed to the destination gateway
* [x] approve_message - Relay an approval into the destination gateway
* [x] distributeRewards - Trigger the Axelar Network to pay rewards out to verifiers based on contribution and current pay per epoch rate
* [x] deploy_source_gateway - Push a new gateway to an EVM chain
* [x] submitGovernanceRequest - Request governance approval for joining Amplifier
    * [x] Verifier
    * [x] Amplifier Routing
    * [x] CosmWasm Approval
    * [x] CosmWasm Deployment
    * [x] CosmWasm Instantiation
* [x] calculate Rewards - how are rewards calculated
* [x] instantiateContracts
* [x] runTofnd
* [x] checkPoolBalances - how do I check the balance of a pool on the Axelar Network (https://github.com/axelarnetwork/axelar-docs/pull/979/files)
* [x] downloadAmpd
* [x] configureAmpd
* [x] downloadAxelard
* [x] printVerifierAddress

(later)
* [ ] Gas service data sending
* [ ] AxelarScan data ingest

**Comment by ffe9f8** [comment]
Duplicated in [Amplifier doc plan](https://docs.google.com/document/d/1kuAjIjEjKqHGxOj5WwLtjfNlaPPDEXRIRHbXkqHw6pk/edit)

**Comment by StephenFluin** [comment]
@ffe9f8 can you please have GitHub be the source of truth for this so that it's public? Just update the checklist for now, but in the future let's try to use GitHub.
