### ISSUE TITLE
Update code for building Amplifier contracts with Docker

### ISSUE THREAD

**Issue by ffe9f8** [axelarnetwork/axelar-docs#1057]
Step two of [Option 2: Build and deploy the contracts yourself](https://docs.axelar.dev/dev/amplifier/chain-integration/integrate-a-chain#option-2-build-and-deploy-the-contracts-yourself) is outdated.

Running

```
docker run --rm -v "$(pwd)":/code \
--mount type=volume,source="$(basename "$(pwd)")_cache",target=/target \
--mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
cosmwasm/optimizer:0.15.1
```

gets the following error:

```
error: package `msgs-derive v0.1.0 (/code/packages/msgs-derive)` cannot be built because it requires rustc 1.78.0 or newer, while the currently active rustc version is 1.75.0

thread 'main' panicked at src/lib.rs:81:9:
assertion failed: error_code.success()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My machine is running `rustc 1.79.0` and `cargo 1.79.0`.

**Comment by StephenFluin** [comment]
@ffe9f8 Try with 0.16.0? Looks like the new latest per here: https://hub.docker.com/r/cosmwasm/optimizer/tags
