### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by TimGuo7** [axelarnetwork/axelar-docs#1150]
https://www.axelar.network/its 
<img width="818" alt="image" src="https://github.com/user-attachments/assets/1ca2991b-5f94-4601-b50a-cb91e9f58656">
when you click read the docs here that's blank and we cannot access the page.  
<img width="824" alt="image" src="https://github.com/user-attachments/assets/4b362901-6c9c-4614-bbd7-b220f105574f">

**Comment by benjamin852** [comment]
[fixed ](https://github.com/axelarnetwork/axelar-docs/pull/1155)
