### ISSUE TITLE
Feedback for “Mainnet | Axelar Network”

### ISSUE THREAD

**Issue by G-Gamja** [axelarnetwork/axelar-docs#323]
How can I get some data that allows to know which tokens cannot be received on which chains. As an example, we cannot send axlWMATIC tokens from the Axeler chain to the Ethereum chain. Is there an API provided by Axelar?

**Comment by StephenFluin** [comment]
@G-Gamja I would look at https://docs.axelar.dev/resources/mainnet#assets which is the canonical place to see which assets are supported on which chains.  You should also be able to explore this information in the [Satellite UI](https://satellite.money) interface.
