### ISSUE TITLE
Feedback for “Get a deposit address”

### ISSUE THREAD

**Issue by radekskrabucha** [axelarnetwork/axelar-docs#376]
I want to send native asset and get wrapped asset on destination chain, like here https://docs.axelar.dev/dev/axelarjs-sdk/token-transfer-dep-addr#3-send-native-tokens-from-a-evm-chain.
Same exact example like in docs: `I want to send AVAX on Avalanche and receive the equivalent ERC-20 version on Polygon`. And I'm doing this on testnet.

My question is what should be in `asset`. When I'm sending some ERC-20 tokens the asset should be denom, e.g. `axlUSDC `  👉 `uausdc `. 
In the example from your docs when sending native AVAX the `asset` is `avax`. Where does it come from? What is this value? What about other chains?

**Comment by radekskrabucha** [comment]
Also when the `asset` is `avax` like in docs I'm gettin an error
<img width="630" alt="image" src="https://user-images.githubusercontent.com/81694334/229953723-241bc78a-b3d7-4cce-ade3-8d8fabf9bfbf.png">
any idea what is this error? It's only when I try to `generateDepositAddress` with native asset, when `asset` is some denom for ERC-20 token then it's fine

**Comment by StephenFluin** [comment]
The native assets are listed here, but we'll add them to the docs soon:

https://github.com/axelarnetwork/axelarjs-sdk/blob/main/src/libs/types/index.ts#L134.

Related to your error, can you confirm the API endpoint is sending a result successfully? We've had issues where our DDOS protection provider is blocking API traffic. If that's the case, we can get you added to the allow-list.
