### ISSUE TITLE
Feedback for “General Flow of Events processed by Axelar Network”

### ISSUE THREAD

**Issue by zlaoxie** [axelarnetwork/axelar-docs#395]
Is there an outage today? Apparently some bridging from Polygon is stucked at the Axelar end..
Transaction details: https://axelarscan.io/gmp/0xd57532e38059b4492c70e96b635445efa9c405eb9e033652913364379cb8c748

**Comment by Olanetsoft** [comment]
Hello @zlaoxie,

I apologize for any inconvenience caused by the experience you had. Upon reviewing the transaction details, I saw that everything proceeded as expected. Please let me know if there is anything else I can help with.
