### ISSUE TITLE
Broken links in pay-gas page

### ISSUE THREAD

**Issue by ori-wagmi** [axelarnetwork/axelar-docs#417]
https://docs.axelar.dev/dev/general-message-passing/gas-services/pay-gas#alternative-gas-payment-methods-for-callcontractwithtoken

In the section:
```
**payGasForContractCallWithToken**

This method receives any tokens for the relayer fee. 
The paid gas for this method must be in tokens Axelar supports. See the list of supported assets: 
[Mainnet](https://docs.axelar.dev/dev/general-message-passing/reference/mainnet-contract-addresses) | 
[Testnet](https://docs.axelar.dev/dev/general-message-passing/reference/testnet-contract-addresses).
```

Mainnet and Testnet links are broken

**Comment by Olanetsoft** [comment]
@ori-wagmi Thank you for bringing this to our attention. We appreciate your effort in identifying the broken links on the pay-gas page. We have already started working on the issue, and we will keep you updated on the progress.

Please let us know if you have any other issues or feedback.

Thank you again for your contributions to our project.
