### ISSUE TITLE
Migrate to a new documentation infrastructure

### ISSUE THREAD

**Issue by StephenFluin** [axelarnetwork/axelar-docs#456]
Preview here: https://axelar-documentation.vercel.app/resources/mainnet

Goals:

* [x] Customizability of template
* [x] Arbitrary JS Execution
* [x] Algolia Search
* [x] Faster / More Reliable builds

Bugs
* [x] Keplr Add to wallet buttons
* [x] CSS on resources page
* [x] Search priority for non-CLI docs
* [x] CLI docs navigation
* [x] Remove markdown from search index
* [x] Add SEO redirects

Steps:
* [x] Migrate markdown files
* [x] Migrate React Components
    * [x] `could not find react-redux context value; please ensure the component is wrapped in a <Provider>`
* [x] Match Styling
* [x] Ensure SEO
* [x] Add Algolia
    * [x] Index auto-generation
    * [x] Index auto-upload
    * [x] Search Results UX
* [x] Automatically styled code previews with copy button
* [x] noreferrer noopener
* [x] Dynamic Algolia Re-ranking

**Comment by benjamin852** [comment]
Reminder from our call earlier today: 
1. Our list of all the contract addresses should have a copy button on this page + for testnet page -> (https://axelar-documentation.vercel.app/resources/mainnet)
2.  (On the same page) If a user clicks on an asset then the dropdown menu comes on top of the table with their assets (see img)

<img width="997" alt="docs-table-menu-bug" src="https://github.com/axelarnetwork/axelar-docs/assets/13651771/b6996f05-846d-4d8e-8a23-f4e5564a1e45">

**Comment by StephenFluin** [comment]
Algolia insights seems to be blocked - no action needed.

Dark mode can come later IMO (I prefer dark mode personally), but I want to ship then improve.

I didn't quite agree /understand your FAQ feedback, looks similar to the docs today?

**Comment by StephenFluin** [comment]
@benjamin852 @Olanetsoft Want to give it another look through? I think I've hit every item.

**Comment by Olanetsoft** [comment]
The appearance seems improved and more polished. I did notice a few minor things:

* [ ] Styling/design on the https://axelar-documentation.vercel.app/resources/ page looks off.

![Screenshot 2023-08-04 at 11 49 56](https://github.com/axelarnetwork/axelar-docs/assets/45847909/4291f784-fa71-407c-b3fc-e1943e2fcd2c)

* [ ] I noticed that most code examples aren't highlighted as code.
![Screenshot 2023-08-04 at 11 57 28](https://github.com/axelarnetwork/axelar-docs/assets/45847909/1936a0f8-faa3-4c7f-8092-3571757c4be2)

* [ ] Minor fix here: https://axelar-documentation.vercel.app/node/join-genesis. 
![Screenshot 2023-08-04 at 12 19 00](https://github.com/axelarnetwork/axelar-docs/assets/45847909/b5a8cb81-3ccc-44d4-a994-3b088115e4f1)

**Comment by alanrsoares** [comment]
Browser: brave
OS: pop-os

- [ ] fonts not loading correctly 
- [ ] gap between footer and the bottom of the page

![image_720](https://github.com/axelarnetwork/axelar-docs/assets/273334/516c300e-fb1e-4c1c-8c8a-b93f9c7d427e)

**Comment by StephenFluin** [comment]
@Olanetsoft 
> Minor fix here: https://axelar-documentation.vercel.app/node/join-genesis.

This is Working as Intended (WAI). The table doesn't look good and is harder to read stretched out.

**Comment by StephenFluin** [comment]
Fixed in 8b22e4392d0f7d69f6f716cbb79e79068e546d85.
