### ISSUE TITLE
In Constant Address Deployer guide add note about msg.sender

### ISSUE THREAD

**Issue by SKYBITDev3** [axelarnetwork/axelar-docs#509]
As I mentioned in https://github.com/axelarnetwork/interchain-token-service/issues/100#issuecomment-1682827514 , when using a factory (e.g. [Constant Address Deployer](https://docs.axelar.dev/dev/general-message-passing/solidity-utilities#constant-address-deployer)) to deploy a contract, `msg.sender` may be the factory's (or a temporary proxy's) address instead of the address of the account doing the deployment.

So there should be an important note about this in the documentation.

The best solution is to pass in the address to the constructor and use that instead of using `msg.sender`.

So for example this code:
```solidity
    constructor() ERC20("MyToken", "MTK") {
        _mint(msg.sender, 1000000000 * 10 ** decimals());
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
    }
```
should be changed to:
```solidity
    constructor(address adminAddress) ERC20("MyToken", "MTK") {
        _mint(adminAddress, 1000000000 * 10 ** decimals());
        _grantRole(DEFAULT_ADMIN_ROLE, adminAddress);
    }
```

**Comment by re1ro** [comment]
Yeah that's obvious that message sender is the factory if you use it. The Sample Token is an example code meant to give a general idea how token integrates with ITS. It's stated there that example code is not meant for direct copy paste into any serious project. There is general expectation of developers understanding what are they doing when implementing production grade custom interchain tokens.
