### ISSUE TITLE
Visual issues on resource page

### ISSUE THREAD

**Issue by npty** [axelarnetwork/axelar-docs#536]
1. Text color for token symbol / chain name in dark mode 

![image (1)](https://github.com/axelarnetwork/axelar-docs/assets/78221556/bcaee8ac-4973-4359-8b89-e1578b028488)

2. Duplicated asset

![Screenshot 2566-09-01 at 9 41 41 PM](https://github.com/axelarnetwork/axelar-docs/assets/78221556/11be1df3-520d-4d9f-bf43-c0905bb23ae0)

3. Broken token image link

![image (2)](https://github.com/axelarnetwork/axelar-docs/assets/78221556/032fd2f8-0374-4081-8895-330ea32c697d)

**Comment by StephenFluin** [comment]
Point 1 is fixed.
Point 2 can't be reproduced, likely an unrelated data error.
Point 3 can't be reproduced

@npty
