### ISSUE TITLE
fix: mobile menu design

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelar-docs#552]
On mobile, the menu design appears differently, as shown below.

![Screenshot_20230911_172010_Chrome](https://github.com/axelarnetwork/axelar-docs/assets/45847909/d7709f95-89b6-429f-a601-4260299d261d)
![Screenshot_20230911_172005_Chrome](https://github.com/axelarnetwork/axelar-docs/assets/45847909/33c3a198-81ef-41f7-a528-7e329f3a8367)

**Comment by Code-Victor** [comment]
I'm interested in working on this.

**Comment by StephenFluin** [comment]
This was previously fixed.
