### ISSUE TITLE
fix mobile responsiveness for mainnet contract address page

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelar-docs#568]
![Screenshot_20230919_174046_Chrome](https://github.com/axelarnetwork/axelar-docs/assets/45847909/dfa44c25-066f-4d7c-b78e-639e9bddf6bc)

**Comment by Code-Victor** [comment]
I'm interested in working on this.

**Comment by StephenFluin** [comment]
@Code-Victor We'd love a PR! Let us know if you need any help.

**Comment by Code-Victor** [comment]
Thanks, @StephenFluin, I just created one. You can check it and give me a feedback👍
