### ISSUE TITLE
Reorder chains in resources alphabetically

### ISSUE THREAD

**Issue by milapsheth** [axelarnetwork/axelar-docs#587]
Reorder chains alphabetically in the config so they appear the same under resources. Could also do by popularity but requires more maintenance.

https://github.com/axelarnetwork/axelar-docs/blob/main/src/data/evm_chains.json

**Comment by ffe9f8** [comment]
Done in [PR 720](https://github.com/axelarnetwork/axelar-docs/pull/720/files).
