### ISSUE TITLE
Get i18n working with redirects in production

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/axelar-docs#6]
There seems to be a bug in next.js that causes redirects to break if i18n is also used, but only in production (not localhost).

Example: this commit fixes redirects, but only on local host: https://github.com/axelarnetwork/axelar-docs/commit/e3d49168eadb7f0063c4e5875ba967d5e89f986f
In production deployment https://axelar-docs-rg9732fgz-axelar-network.vercel.app/ we see the following broken redirects:

- `releases/mainnet` -> `resources/mainnet.en-US`
- `resources/mainnet-releases` -> 404 error

The only workaround I found is to remove i18n.  See different fix attempts in #4 and related next.js issues:
https://github.com/vercel/next.js/issues/28921
https://github.com/vercel/next.js/issues/18795
https://github.com/vercel/next.js/issues/18349

**Comment by talalashraf** [comment]
@vladwulf can you see if this is still valid ?

**Comment by StephenFluin** [comment]
Closing as outdated. Our docs don't formally support any other languages currently.
