### ISSUE TITLE
feat: add reference to ITS examples from axelar-example to docs

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelar-docs#726]
https://github.com/axelarnetwork/axelar-examples/tree/main/examples/evm

**Comment by ffe9f8** [comment]
Pages to change:

* [Upgrade Token](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/upgrade-tokens)
* [Create Token](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/create-token)

[Text to change](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/upgrade-tokens#:~:text=You%20can%20try%20our%20sample%20custom%20token%20as%20a%20starting%20point.)

Tell the dev to check out the READMEs in the ITS-related samples in [axelar-examples](https://github.com/axelarnetwork/axelar-examples/tree/main/examples/evm)

**Comment by ffe9f8** [comment]
https://github.com/axelarnetwork/axelar-docs/pull/735
