### ISSUE TITLE
Avalanche

### ISSUE THREAD

**Issue by AntonMashnin** [axelarnetwork/axelar-docs#8]
- Avalanche - to properly run of the Avalanche node we have added manually the following line to the file:  /home/avax/.avalanche go/configs/node.json

`"network-id": "fuji"`

without it the node is not running, so the final version of the file looks like this:
`{
  "public-ip": "95.217.236.137",
  "http-host": "",
  "network-id": "fuji"
`}

Please update the documentation

**Comment by ggutoski** [comment]
This is already in existing docs:
> Change network-id to `"fuji"`...
