### ISSUE TITLE
All Assets Button Bug

### ISSUE THREAD

**Issue by benjamin852** [axelarnetwork/axelar-docs#817]
Came across a bug where if you click on all assets you are not able to see the address of the tokens. This occurs for all chains but only for mainnet, testnet is fine.

<img width="819" alt="Screenshot 2024-03-06 at 12 03 18 PM" src="https://github.com/axelarnetwork/axelar-docs/assets/13651771/c34051b7-3bdb-4ba0-b057-a5a8e4a38c47">

**Comment by benjamin852** [comment]
Not a logic bug but an issue in the UI. Basically some tokens have super long denoms which distorts the entire table, LVM for example has a path of `
factory/osmo1mlng7pz4pnyxtpq0akfwall37czyk9lukaucsrn30ameplhhshtqdvfm5c/ulvn` and it makes the table look off as a result. I can see if I can wrap this but let me know what you guys think @StephenFluin and @ffe9f8  before I take a run at changing the css here.

**Comment by ffe9f8** [comment]
I think wrapping would be good.
