### ISSUE TITLE
Sandbox link is broken

### ISSUE THREAD

**Issue by StephenFluin** [axelarnetwork/axelar-docs#823]
Sandbox linked from nav.

https://docs.axelar.dev/dev/general-message-passing/axelar-sandbox/intro

This page isn’t working
docs.axelar.dev redirected you too many times.
[Try deleting your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS

**Comment by ffe9f8** [comment]
Caused by this redirect further down on `vercel.json`:

```
  {
    "source": "/dev/axelar-sandbox/:path(.*)",
    "destination": "/dev/general-message-passing/axelar-sandbox/:path",
    "permanent": true
  },
```

[PR 825](https://github.com/axelarnetwork/axelar-docs/pull/825) to fix.
