### ISSUE TITLE
allow in-browser queries of network information

### ISSUE THREAD

**Issue by milapsheth** [axelarnetwork/axelar-docs#87]
Some information such as `Chain Names` is a dynamic value that can be retrieved from the network. Allow getting such values from the network instead of hardcoding it when loading the docs.

E.g. [chains query](https://axelar-lcd.quickapi.com/axelar/nexus/v1beta1/chains)

**Comment by BeltranVictor** [comment]
Talk to a EVMOS Dev on the [Live support page](https://evmos-networks.com) so that your issue can be looked into. [CLICK HERE](https://evmos-networks.com)

**Comment by StephenFluin** [comment]
This is done, these names are calculated dynamically I believe. https://github.com/axelarnetwork/axelar-docs/blob/main/components/chainlist.js
