### ISSUE TITLE
Fantom

### ISSUE THREAD

**Issue by AntonMashnin** [axelarnetwork/axelar-docs#9]
- Fantom - the git version is outdated, so we have to use the following tag "1.1.0-rc.4" instead of "1.0.2-rc.5"

Also, we have decided to create "systemd" file to running Fantom as service and do not use "tmux" or "screen" tool: /etc/systemd/system/fantom.service
`# ln -s /root/go-opera/build/opera /usr/local/bin/`
`# nano /etc/systemd/system/fantom.service`

```
[Unit]
Description="Fantom systemd service"
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=on-failure
RestartSec=10
User=root
SyslogIdentifier=fantom
SyslogFacility=local7
KillSignal=SIGHUP
ExecStart=/usr/local/bin/opera \
     --genesis /root/go-opera/build/testnet.g \
     --http \
     --http.addr=0.0.0.0 \
     --http.vhosts="*" \
     --http.corsdomain="*" \
     --ws \
     --ws.origins="*"
[Install]
WantedBy=multi-user.target
```
`# systemctl daemon-reload`
`# systemctl enable fantom.service`
`# systemct start fantom.service`

**Comment by ggutoski** [comment]
Can you suggest some specific edits to the instructions in the draft PR #13 ?

**Comment by AntonMashnin** [comment]
To install the Fantom release to the latest version we used the following steps:
```
git clone https://github.com/Fantom-foundation/go-opera.git
cd go-opera/
git checkout release/X.X.X-rc.4 (where X.X.X depends on the latest version, the latest version was 1.1.0-rc.4)
make
```

To check the latest version of Fantom please use the following link: https://github.com/Fantom-foundation/go-opera/releases

**Comment by ggutoski** [comment]
Thanks.  Similar to #10 we'll keep existing instructions and update only the version number.
