### ISSUE TITLE
amplifier system requirements

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelar-docs#918]
On our amplifer pages, we should list minimal system requirements, e.g. a partner raised this issue: 

<img width="1269" alt="image" src="https://github.com/axelarnetwork/axelar-docs/assets/17285185/919f01b3-6be1-4caf-943d-8c345331874f">

**Comment by ffe9f8** [comment]
To clarify, devs need to have rustc 1.75.0 or newer installed to become an integrator / verifier?
