### ISSUE TITLE
amplifier gas prices

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelar-docs#919]
we need to specify gas prices in all amplifier commands, e.g. 

`axelard tx wasm store artifacts/voting_verifier.wasm --node http://devnet-amplifier.axelar.dev:26657 --from wallet --chain-id devnet-amplifier --gas auto --gas-adjustment 1.5 --keyring-backend test`

=> 

`axelard tx wasm store artifacts/voting_verifier.wasm --node http://devnet-amplifier.axelar.dev:26657 --from wallet --chain-id devnet-amplifier --gas-prices 0.007uamplifier --gas auto --gas-adjustment 1.5 --keyring-backend test
`

**Comment by ffe9f8** [comment]
[Context](https://interoplabs.slack.com/archives/C04K4J95GKC/p1712805240229689)

**Comment by ffe9f8** [comment]
Perhaps they should also remove `--gas auto`? So it would look something like this instead:

```
axelard tx wasm store target/wasm32-unknown-unknown/release/voting_verifier.wasm --node http://devnet-amplifier.axelar.dev:26657/ --from wallet --chain-id devnet-amplifier --gas-prices 0.007uamplifier
```

[Context](https://interoplabs.slack.com/archives/C06SYJ5CPFF/p1712785013269229?thread_ts=1712775816.567459&cid=C06SYJ5CPFF)
