### ISSUE TITLE
amplifier ampd release version

### ISSUE THREAD

**Issue by canhtrinh** [axelarnetwork/axelar-docs#930]
clarify that the version people are running this https://docs.axelar.dev/dev/amplifier/chain-integration#option-2-build-and-deploy-the-contracts-yourself

on should be based on this release: https://github.com/axelarnetwork/axelar-amplifier/releases/tag/ampd-v0.1.0

and not the main branch

**Comment by ffe9f8** [comment]
Now here: https://docs.axelar.dev/dev/amplifier/chain-integration/integrate-a-chain#option-2-build-and-deploy-the-contracts-yourself

**Comment by StephenFluin** [comment]
Fixed in #932
