### ISSUE TITLE
Requested changes to on-chain gas estimation docs

### ISSUE THREAD

**Issue by StephenFluin** [axelarnetwork/axelar-docs#949]
- [x] We don’t need to distinguish estimator from the gas service. The gas service allows estimation, and IAxelarGasService exposes estimateGasFee already
 - [x] Maybe create a constant for the executionGasLimit = 200000 to be more explicit that this is the fixed execution gas on destination.
 
The purpose of the example is a bit confusing.

The goal of on-chain gas estimation isn’t to refund the user with the difference right away as done by this example. The on-chain gas estimate can and will likely overestimate the actual gas to account for volatility. The refund should be left to the relayer (the example specifies msg.sender as the refund address already), otherwise the user is just paying for two refunds unnecessarily.

Also, there’s no need to call estimateGasFee explicitly. payGas is calling estimateGasFee internally is estimateOnChain param is set to true as shown in the spec’s example. msg.value can be forwarded directly, and it’ll revert if not sufficient, and overestimate will be refunded by the relayer.

But the doc doesn’t showcase the fully on-chain use of on chain gas estimate, where the contract calls estimateGasFee and forwards that amount from it’s own balance, instead of msg.value (the caller). Could be a separate example that we showcase.

You can refer to [this PR](https://github.com/axelarnetwork/axelar-examples/pull/175) to axelar-examples that showcases the above, cc Kiryl to update it
The doc is also missing a note on how to get guaranteed execution, and other caveats like the on-chain gas quotes will be higher than off-chain to account for volatility.

Also needs a link to a form where devs can submit contract addresses for whitelisting on axelarons for guaranteed execution (or a note to contact us if we don’t want to expose the info publicly for now but let partners know explicitly)

**Comment by StephenFluin** [comment]
@milapsheth 

I completely agree the purpose of the on-chain gas estimates aren't for refunds. The purpose of this smart contract is to teach how to use the gas estimation, which would be much harder if developers were expected to deploy and then fund the smart contract in order to use it (I've seen devs often fail at this when learning new concepts).

The reason the idea of an "instant refund" was chosen rather than relying on the `estimateGasFee` to take the whole value and return it later via the relayer is that it shows an application of the estimate immediately. This actually also helps with demos of GMP and on-chain gas estimation because you don't need to build separate infrastructure (or another contract) to separately estimate gas, you can just dramatically overfund and be 100% certain you will end the transaction without overpaying.

We can definitely add another example of forwarding value from the contract itself, but you won't be able to deploy or use it without more work, so we can add that if you would like, or we can just link to axelar-examples once https://github.com/axelarnetwork/axelar-examples/pull/175 is merged.

My understanding was that guaranteed execution is not generally available or something developers should be asking about, is that wrong?

**Comment by milapsheth** [comment]
> @milapsheth
> 
> I completely agree the purpose of the on-chain gas estimates aren't for refunds. The purpose of this smart contract is to teach how to use the gas estimation, which would be much harder if developers were expected to deploy and then fund the smart contract in order to use it (I've seen devs often fail at this when learning new concepts).
> 
> The reason the idea of an "instant refund" was chosen rather than relying on the `estimateGasFee` to take the whole value and return it later via the relayer is that it shows an application of the estimate immediately. This actually also helps with demos of GMP and on-chain gas estimation because you don't need to build separate infrastructure (or another contract) to separately estimate gas, you can just dramatically overfund and be 100% certain you will end the transaction without overpaying.

I would not recommend showcasing a pattern of overfunding and using an instant refund. It requires the user to have a lot more funds in their wallet to initiate the tx (even if it's refunded later). Also, the user making the tx sees this overfunded amount when they approve it (seeing a contract ask them for hundreds of dollars worth of tokens can be quite concerning to the user, and it's not obvious to them that they'll be refunded). It's hard to do "reasonable" overfunding as well. For e.g. to overfund by 2x still requires knowing what the actual estimate. During periods of volatility the gas prices can fluctuate quite a lot (5x for ethereum, 50-100x for fantom etc.) which would cause these txs to fail for the app and lose liveness if the static overfunding value isn't enough.

> We can definitely add another example of forwarding value from the contract itself, but you won't be able to deploy or use it without more work, so we can add that if you would like, or we can just link to axelar-examples once [axelarnetwork/axelar-examples#175](https://github.com/axelarnetwork/axelar-examples/pull/175) is merged.

What I proposed was to have to two separate examples. The first example is the open PR we have (feel free to improve it) showcasing the normal GMP use case of someone querying just the contract for the estimate and paying it, and another (if needed) with the more complex setup of the contract paying by itself.

> My understanding was that guaranteed execution is not generally available or something developers should be asking about, is that wrong?

Not generally available, but we can create an intake form for partners who want to use it and provide their contracts. We can expand in the future if needed. We should mention though that execution is not guaranteed in the docs when using this (and maybe ask devs to contact us in discord or something if they require it, or link to the form in docs)
